name: hashtag_mqtt
description: hashtag_mqtt

module:
  androidPackage: com.hashtag.mqtt
  iosBundleIdentifier: com.hashtag.mqtt

publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: "3.10.2"
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.2
  dio: ^5.2.0
  equatable: ^2.0.5

  #firebase
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_database: ^10.2.2
  firebase_dynamic_links: ^5.3.2
  firebase_messaging: ^14.6.2
  firebase_remote_config: ^4.2.2

  #flutter
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6

  #get
  get: ^4.6.5
  get_storage: ^2.1.1

  google_fonts: ^4.0.4
  package_info_plus: ^4.0.2
  permission_handler: ^10.2.0
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/app_icon.png"
  image_path_android: "assets/launcher/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app/
    - assets/launcher/



