// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClr0Th6pY8Ds8oShxzUBg2aNkIyjjMspo',
    appId: '1:468912544522:web:b425e6bf741151c73e38f3',
    messagingSenderId: '468912544522',
    projectId: 'hashtag-mqtt',
    authDomain: 'hashtag-mqtt.firebaseapp.com',
    databaseURL: 'https://hashtag-mqtt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hashtag-mqtt.appspot.com',
    measurementId: 'G-VMHJNTQG86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6odst2tqb53vgB11Cb5WKCMLevIGDbUY',
    appId: '1:468912544522:android:b8e84319bbf5928e3e38f3',
    messagingSenderId: '468912544522',
    projectId: 'hashtag-mqtt',
    databaseURL: 'https://hashtag-mqtt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hashtag-mqtt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAV-ufn7Ne9ho3gAho5J71SQw_ogxpxMU',
    appId: '1:468912544522:ios:73e986ff4d9c5cdf3e38f3',
    messagingSenderId: '468912544522',
    projectId: 'hashtag-mqtt',
    databaseURL: 'https://hashtag-mqtt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hashtag-mqtt.appspot.com',
    iosClientId: '468912544522-ktf0imeglt6h7flahfaankcplk6dnso9.apps.googleusercontent.com',
    iosBundleId: 'com.hashtag.mqtt.hashtagMqtt',
  );
}
